# GITHUB_TOKEN environment variable is required to build the images

version: '3'

volumes:
  build-user-builds:
  azurite_data:
  postgres_data:
  postgres_backups_data:

services:
  server:
    # Image used for all the other services (proxito, web, celery, build)
    build:
      context: .
      dockerfile: ${PWD}/docker/Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}

  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - web
      - proxito
      - storage
    volumes:
      - ${PWD}/docker/nginx:/etc/nginx/conf.d

  proxito:
    image: readthedocsorg_server:latest
    volumes:
      - ${PWD}:/usr/src/app/checkouts/readthedocs.org
      - ${PWD}/../readthedocs-ext:/usr/src/app/checkouts/readthedocs-ext
      - ${PWD}/docker/settings/proxito.py:/usr/src/app/checkouts/readthedocs.org/readthedocs/settings/proxito.py
    links:
      - storage
      - database
      - cache
    environment:
      - DJANGO_SETTINGS_MODULE=readthedocs.settings.proxito
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]

  web:
    image: readthedocsorg_server:latest
    volumes:
      - ${PWD}/docker/entrypoints/web.sh:/usr/src/app/docker/web.sh
      - ${PWD}/../readthedocs-ext:/usr/src/app/checkouts/readthedocs-ext
      - ${PWD}:/usr/src/app/checkouts/readthedocs.org
      - ${PWD}/docker/settings/web.py:/usr/src/app/checkouts/readthedocs.org/readthedocs/settings/web.py
    links:
      - storage
      - database
      - cache
    depends_on:
      - storage
      - azure-cli
    environment:
      - DJANGO_SETTINGS_MODULE=readthedocs.settings.web
    command: ["../../docker/web.sh"]

  celery:
    image: readthedocsorg_server:latest
    volumes:
      - ${PWD}/docker/entrypoints/celery.sh:/usr/src/app/docker/celery.sh
      - ${PWD}/../readthedocs-ext:/usr/src/app/checkouts/readthedocs-ext
      - ${PWD}:/usr/src/app/checkouts/readthedocs.org
      - ${PWD}/docker/settings/celery.py:/usr/src/app/checkouts/readthedocs.org/readthedocs/settings/celery.py
    links:
      - storage
      - database
      - cache
    depends_on:
      - storage
      - azure-cli
    environment:
      - DJANGO_SETTINGS_MODULE=readthedocs.settings.celery
    command: ["../../docker/celery.sh"]

  build:
    image: readthedocsorg_server:latest
    volumes:
      - ${PWD}/docker/entrypoints/build.sh:/usr/src/app/docker/build.sh
      - ${PWD}/../readthedocs-ext:/usr/src/app/checkouts/readthedocs-ext
      - ${PWD}:/usr/src/app/checkouts/readthedocs.org
      - ${PWD}/docker/settings/build.py:/usr/src/app/checkouts/readthedocs.org/readthedocs/settings/build.py

      # The python code at readthedocs/doc_builder/environments.py
      # mounts `self.project.doc_path`. We need to share this path
      # between the build container (git commands), and the container that
      # is created inside the build container (sphinx commands).
      # Because of this, we need to use a shared volume between them
      - build-user-builds:/usr/src/app/checkouts/readthedocs.org/user_builds

      # Docker in Docker
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - web
      - storage
      - cache
    environment:
      - DJANGO_SETTINGS_MODULE=readthedocs.settings.build
    command: ["../../docker/build.sh"]

  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    volumes:
      - azurite_data:/data
    ports:
      - "10000:10000"
    command: ["azurite-blob", "--silent", "--blobPort", "10000", "--blobHost", "0.0.0.0"]

  azure-cli:
    image: microsoft/azure-cli
    volumes:
      - ${PWD}/docker/scripts/create-containers.sh:/usr/local/bin/create-containers.sh
    links:
      - storage
    depends_on:
      - storage
    command: ["/usr/local/bin/create-containers.sh"]

  cache:
    image: redis:3.2.7

  database:
    image: postgres:11.1
    environment:
      - POSTGRES_USER=docs_user
      - POSTGRES_PASSWORD=docs_pwd
      - POSTGRES_DB=docs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups_data:/backups
