# docker-compose-search.yml starts "search" service and override some
# services to link them so they can use the "search" as well.
version: '3'

volumes:
  search_data:

services:

  web:
    links:
      - storage
      - database
      - cache
      - search

  celery:
    links:
      - storage
      - database
      - cache
      - search

  # You may need to increase the memory for vm
  # sudo sysctl -w vm.max_map_count=262144
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - discovery.type=single-node
    volumes:
      - search_data:/usr/share/elasticsearch/data
