version: 2.1

default: &default
  steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init
    - run: pip install --user tox
    - run: scripts/circle/install_node.sh
    - run:
        name: Add node to the path
        command: |
          echo 'export PATH=~/.nvm/versions/node/v${NODE_VERSION}/bin:$PATH' >> $BASH_ENV
          source $BASH_ENV
    - run: tox

jobs:
  tests:
    <<: *default
    docker:
      - image: 'cimg/python:3.6'
        environment:
          TOXENV: py36,codecov
          TOX_POSARGS: ''
      - image: 'docker.elastic.co/elasticsearch/elasticsearch:6.8.12'
        name: search

  lint:
    <<: *default
    docker:
      - image: 'cimg/python:3.6'
        environment:
          TOXENV: lint

  migrations:
    <<: *default
    docker:
      - image: 'cimg/python:3.6'
        environment:
          TOXENV: migrations

  docs:
    <<: *default
    docker:
      - image: 'cimg/python:3.6'
        environment:
          TOXENV: docs

  docs-lint:
    <<: *default
    docker:
      - image: 'cimg/python:3.6'
        environment:
          TOXENV: docs-lint

  eslint:
    <<: *default
    docker:
      - image: 'cimg/python:3.6'
        environment:
          TOXENV: eslint
          NODE_VERSION: 10.17.0

workflows:
  version: 2
  test:
    jobs:
      - lint
      - migrations
      - docs
      - docs-lint
      - eslint
      - tests
